language: c

jobs:
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    dist: xenial
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=linux DEPLOY=linux
  - os: linux
    dist: xenial # Oldest still-supported LTS right now against which the AppImage is built. Update this to the next LTS when support drops.
    name: Linux AppImage
    compiler: gcc
    env: BUILD_TARGET=appimage DEPLOY=appimage
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=mac DEPLOY=mac
  - os: linux
    name: PS Vita
    env: BUILD_TARGET=vita DEPLOY=vita
  - os: linux
    name: Nintendo Switch
    env: BUILD_TARGET=switch DEPLOY=switch
cache:
  directories:
  - "$SDL_LIB"
  - "$SDL_MIXER_LIB"
  - ./.ci_scripts/setup_environment.sh
  - ./.ci_scripts/install_sdl.sh;

before_script:
- "./.ci_scripts/run_cmake.sh"
script:
- "./.ci_scripts/run_build.sh"
after_success:
- if [ $RUN_CODECOV ]; then bash <(curl -s https://codecov.io/bash); fi;
before_deploy:
- "./.ci_scripts/bintray_conf.sh"
deploy:
  provider: bintray
  on:
    all_branches: true
    repo: Keriew/julius
    condition: "$DEPLOY"
  file: bintray.json
  user: keriew
  skip_cleanup: true
  key: 92abc2b88217abc81de1eeba37e5066a0baa6a25
after_deploy:
- "./.ci_scripts/bintray_link.sh"
