language: c
jobs:
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=linux DEPLOY=linux
  - os: linux
    dist: xenial
    name: Linux AppImage
    compiler: gcc
    env: BUILD_TARGET=appimage DEPLOY=appimage
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.12 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=mac DEPLOY=mac
cache:
  directories:
  - "$SDL_LIB"
  - "$SDL_MIXER_LIB"
install:
- "./.ci_scripts/setup_environment.sh"
- "./.ci_scripts/install_sdl.sh;"
before_script:
- "./.ci_scripts/run_cmake.sh"
script:
- "./.ci_scripts/run_build.sh"
after_success:
- if [ $RUN_CODECOV ]; then bash <(curl -s https://codecov.io/bash); fi;
- "./.ci_scripts/create_zipped_release.sh"
before_deploy:
- "./.ci_scripts/bintray_conf.sh"
deploy:
  provider: bintray
  on:
    all_branches: true
    repo: Keriew/augustus
    condition: "$DEPLOY"
  file: bintray.json
  user: keriew
  skip_cleanup: true
  key:
    secure: mHhXXub3p26dJ+ncbfnUr3Ul7vfn7z5RTglCPfjkvseP8OlO5sERx5Nz47hxm6Vph3H6FFd2Zs3NKzMsVtgckf0cCG2WAv05VK5XlL02VYhFsEnlaN6Ce53PhCV5UoNaayH3XEMPRvPAn0AFe+MfaOCEmUpTcJsORx+QxoAgXQHFYj4RXd1AZF+DlDnIEHsdQoZe0uwbcheRu0je5J36aJ55fSHbQjkAkiKW6om8/5Z1EzqeM8UUkeOPkJcTKn+8scWPkQ4MaN4Q24kZZybGzVEXcTD+4YTzlrzGXSU5sCtB2VN+PpBOWmKZ9O4za1vcbXJesDPJT2mXmaoTY37qtKE/TaVVUOThsyvN1A4j4nr80tGxB+eYHnYPL+HZQMy/fJYmuis6ZeNQWjr3v+Ge3Rj/8bPIOmGScJD/58tlYR/AxESpqITws9jxMLuBc+IhTvf3K7GFsgSTioLl0+jkvxylfVDVxLt42RkZ84hA1krkioD9Zu/4AHCLtySkE8EpG4n2ibnvQ2U1O6NaHBAN8klnLzCJqyi24RcKwrxjn9AsYceqss8+mnOaeCHtxpJ+9eS0CxLDaKVCWTSWQzLz+PHqF9VKLoLFXiKscIOZ0FCwXIxcDdgheXrVpkv2DaPd9rXHpGoI4J5rU9djOJAqpykv6NPAO3GCSBBtOzkDdy8=
after_deploy:
- "./.ci_scripts/bintray_link.sh"
