language: c
matrix:
  include:
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.10 SDL_MIXER_LIB=SDL2_mixer-2.0.4 RUN_CODECOV=1
  - os: linux
    compiler: gcc
    env: SDL_LIB=SDL2-2.0.0 SDL_MIXER_LIB=SDL2_mixer-2.0.0
  - os: linux
    compiler: clang
    env: SDL_LIB=SDL2-2.0.10 SDL_MIXER_LIB=SDL2_mixer-2.0.4
  - os: linux
    dist: xenial
    name: Linux AppImage
    compiler: gcc
    sudo: require
    env: BUILD_TARGET=appimage DEPLOY=appimage
    services:
    - docker
  - os: osx
    compiler: clang
    env: SDL_LIB=SDL2-2.0.10 SDL_MIXER_LIB=SDL2_mixer-2.0.4 BUILD_TARGET=mac DEPLOY=mac
  - os: linux
    name: PS Vita
    env: BUILD_TARGET=vita DEPLOY=vita
    services:
    - docker
  - os: linux
    name: Nintendo Switch
    env: BUILD_TARGET=switch DEPLOY=switch
cache:
  directories:
  - "$SDL_LIB"
  - "$SDL_MIXER_LIB"
install:
- "./.ci_scripts/start_docker.sh"
- "./.ci_scripts/install_sdl.sh;"
before_script:
- "./.ci_scripts/run_cmake.sh"
script:
- "./.ci_scripts/run_build.sh"
after_success:
- if [ $RUN_CODECOV ]; then bash <(curl -s https://codecov.io/bash); fi;
before_deploy:
- "./.ci_scripts/bintray_conf.sh"
deploy:
  provider: bintray
  on:
    all_branches: true
    repo: Keriew/julius
    condition: $DEPLOY
  file: bintray.json
  user: keriew
  skip_cleanup: true
  key:
    secure: "HT4ufGFaTRYsYhCeqtBJWdQwtbYxEAwhLQ0fu5TIeIBoX8lnfiRiVwx9gmawc9pq+4AT4OAJoCMu4wHphoXyDfrzeFY7i6d7LL9J15S4JfCH7eOYyTUk00cuqX+lpaciymLnCG3melPAk3kKzxrz/Fg3XSnIw3sahc0cu4zQIsoS7Pbx8xMYvDErB9Oxled9Cvooa0r/z1+IPUpNe6iL5P8CV/XZiv7cGVFtNdVdTIm4DgD2nruo6sesUu4GrMyd1xB3DkhFWXBxWpKe+3Rg4nLnm4hbPKKuyG9mGAuNazeLt4CTeTuw2eZPGJAtfBZMUG9yhS82AT+SZ9rv0Kdb4KIA5k+/9B980jqXY2mKyojPf1hWmBsk1UTUsbASngTxAc91/PcMdrwXRRVb746qhIDnFjfwrJuZScHxOe6mE3MutqBkANOddVVe4PJNHuvj56cVAePpVxGrvSTgsp8jcdbs4eUEsq6MVEi59y4RSRRI75pcQXB1qzAugn5QxdYB3yF4uEfFrpPwvrVTYl5HN3bFWx0308RnrXQHGLT9i3aC9mNLSg00X2zBugJlHhB/kcCvcigEgSCO65MEkXCfkk7L8OpFyh1enbyA5IrgL2Z7wTxBgvZh0+1pqa5fqqMiVH5+mlZFERIQN5HhwhHTS6o86sq8l3hEana/MV7qV8g="
          
after_deploy:
  - ./.ci_scripts/bintray_link.sh
