#define FOOTPRINT_WIDTH 116
#define FOOTPRINT_HALF_WIDTH 58
#define FOOTPRINT_HEIGHT 60
#define FOOTPRINT_HALF_HEIGHT 30

#define TILE_WIDTH_PIXELS 120
#define TILE_HEIGHT_PIXELS 60
#define HALF_TILE_WIDTH_PIXELS 60
#define HALF_TILE_HEIGHT_PIXELS 30

#define GRID_IMAGE "Grid_Full_Large"